# -*- coding: utf-8 -*-
"""
공통 헬퍼 — URL 생성, Playwright 점수 추출, 텍스트 파싱, Excel 저장, 로깅.

데스크탑/노트북 구분은 전적으로 gpuId 로 이루어진다. (사용자 제공 예시 URL 에서
데스크탑 5050=1725, 노트북 5050=1726 둘 다 gpuType=ALL & deviceType=ALL 이었음)
따라서 build_url 은 사용자가 준 URL 형식을 그대로 재현한다.
"""
from __future__ import annotations

import asyncio
import logging
import re
import sys
from datetime import datetime
from pathlib import Path
from urllib.parse import urlencode

BASE = "https://www.3dmark.com/search"
# scripts/ 안에 있으므로 프로젝트 루트(부모의 부모)의 output 을 가리킨다.
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "output"

# 지원 벤치마크:  키 → (표시명, 3DMark test 코드)
BENCHMARKS = {
    "timespy":    ("Time Spy",         "spy P"),
    "firestrike": ("Fire Strike",      "fs P"),
    "portroyal":  ("Port Royal",       "pr P"),
    "steelnomad": ("Steel Nomad DX12", "sw DX"),
}

# 결과 행 타입: (시리즈, 모델명, 평균 점수 | None, 총 결과 수 | None, 링크)
Row = "tuple[str, str, int | None, int | None, str]"

# 실제 데스크탑 Chrome UA — headless 봇 탐지/차단 회피용
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

# CloudFront/WAF 차단 페이지 식별 문구
_BLOCK_RE = re.compile(
    r"Request blocked|generated by cloudfront|could not be satisfied"
    r"|403 ERROR|Access Denied|Too Many Requests",
    re.IGNORECASE,
)


class BlockedError(Exception):
    """CloudFront/WAF 에 의해 요청이 차단됐을 때 발생. 재시도 금지, 즉시 중단."""


def bench_dir(kind: str, bench: str) -> Path:
    """결과/로그/진행기록을 저장할 폴더(output/{kind}/{benchmark})."""
    d = OUTPUT_DIR / kind / bench
    d.mkdir(parents=True, exist_ok=True)
    return d


_RE_GPUID = re.compile(r"[?&]gpuId=(\d+)")


def load_latest_result(kind: str, bench: str) -> "tuple[dict[int, tuple], float | None]":
    """
    output/{kind}/{bench}/ 의 가장 최근 결과 xlsx 를 읽어
    {gpuId: (시리즈, 모델명, 평균, 결과수, 링크)} 와 그 파일의 수정시각(epoch)을 반환.
    파일이 없으면 ({}, None).
    """
    d = OUTPUT_DIR / kind / bench
    if not d.exists():
        return {}, None
    files = sorted(d.glob("3dmark_*_scores_*.xlsx"),
                   key=lambda p: p.stat().st_mtime)
    if not files:
        return {}, None
    latest = files[-1]

    from openpyxl import load_workbook
    wb = load_workbook(latest, read_only=True)
    ws = wb.active
    out: "dict[int, tuple]" = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or len(row) < 5:
            continue
        series, model, avg, count, url = row[:5]
        m = _RE_GPUID.search(url or "")
        if m:
            out[int(m.group(1))] = (series, model, avg, count, url)
    wb.close()
    return out, latest.stat().st_mtime


# 점수 텍스트와 무관해 차단해도 되는 리소스/도메인 — 요청 수를 줄여 차단을 예방한다.
# 주의: 구글 차트(gstatic.com/charts)는 통계 텍스트 렌더 콜백에 쓰이므로 막지 않는다.
#       이미지/폰트/미디어(시각 표시 전용)와 분석·광고 도메인만 차단한다.
_SKIP_RESOURCE_TYPES = {"image", "media", "font"}
_SKIP_DOMAINS = (
    "google-analytics.com", "googletagmanager.com", "analytics.google.com",
    "doubleclick.net", "stats.g.doubleclick.net", "nr-data.net",
    "fonts.gstatic.com", "fonts.googleapis.com",
    "getunicorn.org", "trustarc.com",   # 추적 분석 / 쿠키 동의 배너
)


async def _route_filter(route):
    """이미지/폰트/미디어 및 분석·광고 도메인 요청을 막는다 (차트는 허용)."""
    req = route.request
    try:
        if req.resource_type in _SKIP_RESOURCE_TYPES:
            await route.abort()
            return
        if any(d in req.url for d in _SKIP_DOMAINS):
            await route.abort()
            return
        await route.continue_()
    except Exception:  # noqa: BLE001
        # 라우팅 중 페이지가 닫히는 등 경합이 나면 조용히 무시
        pass


async def make_context(browser):
    """봇 탐지를 줄인 브라우저 컨텍스트 생성 (실제 UA / 언어 / 뷰포트 + 리소스 차단)."""
    ctx = await browser.new_context(
        user_agent=USER_AGENT,
        locale="en-US",
        viewport={"width": 1366, "height": 850},
        extra_http_headers={"Accept-Language": "en-US,en;q=0.9"},
    )
    # navigator.webdriver 흔적 제거
    await ctx.add_init_script(
        "Object.defineProperty(navigator,'webdriver',{get:()=>undefined});"
    )
    # 불필요한 리소스 차단 (요청 수↓ → 차단 예방 + 속도↑)
    await ctx.route("**/*", _route_filter)
    return ctx


# ---------------------------------------------------------------------------
# 브라우저 실행 (시스템 Edge)
# ---------------------------------------------------------------------------
# 안티바이러스가 Playwright 번들 Chromium 을 격리/삭제하는 환경이라,
# Windows 기본 설치 브라우저인 Microsoft Edge(Chromium) 를 사용한다.
async def launch_browser(p, log: "logging.Logger | None" = None):
    log = log or logging.getLogger("3dmark")
    try:
        browser = await p.chromium.launch(headless=True, channel="msedge")
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(
            f"Microsoft Edge 실행에 실패했습니다 ({type(e).__name__}). "
            "Edge 가 설치돼 있는지 확인하세요."
        ) from e
    log.info("브라우저: Edge 사용")
    return browser


# ---------------------------------------------------------------------------
# URL 생성
# ---------------------------------------------------------------------------
def build_url(gpu_id: int, test_code: str = "spy P") -> str:
    """
    gpuId / 벤치마크에 대한 Graphics score 검색 URL 을 만든다.
    검색 조건은 hash(#advanced?...) 뒤에 들어가야 SPA 가 인식한다.
    """
    params = [
        ("test", test_code),
        ("cpuId", ""),
        ("gpuId", str(gpu_id)),
        ("gpuCount", "1"),
        ("gpuType", "ALL"),
        ("deviceType", "ALL"),
        ("storageModel", "ALL"),
        ("modelId", ""),
        ("showRamDisks", "false"),
        ("memoryChannels", "0"),
        ("country", ""),
        ("scoreType", "graphicsScore"),
        ("hofMode", "false"),
        ("showInvalidResults", "false"),
        ("freeParams", ""),
        ("minGpuCoreClock", ""),
        ("maxGpuCoreClock", ""),
        ("minGpuMemClock", ""),
        ("maxGpuMemClock", ""),
        ("minCpuClock", ""),
        ("maxCpuClock", ""),
    ]
    return f"{BASE}#advanced?{urlencode(params, safe='')}"


# ---------------------------------------------------------------------------
# 백엔드 통계 API 직접 호출
# ---------------------------------------------------------------------------
# 페이지 전체를 로드하는 대신 점수 통계 ajax 만 호출해 GPU 당 요청 수를 크게 줄인다.
#   - 평균(Average score) = medianscore API 의 median 필드
#   - 결과 수(Found N)     = newsearch  API 의 resultCount 필드
#   - scoreType=graphicsScore 가 URL 파라미터로 바로 적용돼 Graphics 기준이 된다.
# jQuery AJAX 와 동일한 Accept 헤더가 없으면 서버가 406 을 주므로 반드시 지정한다.
# (페이지 컨텍스트 안에서 fetch 하므로 쿠키/Origin 이 자동 적용되어 차단을 회피한다.)
_AJAX_HEADERS = {
    "Accept": "application/json, text/javascript, */*; q=0.01",
    "X-Requested-With": "XMLHttpRequest",
}


def _ajax_query(gpu_id: int, test_code: str = "spy P") -> str:
    return (f"test={test_code}&cpuId=&gpuId={gpu_id}&gpuCount=1&gpuType=ALL&deviceType=ALL"
            "&storageModel=ALL&modelId=&showRamDisks=false&memoryChannels=0&country="
            "&scoreType=graphicsScore&hofMode=false&showInvalidResults=false&freeParams="
            "&minGpuCoreClock=&maxGpuCoreClock=&minGpuMemClock=&maxGpuMemClock="
            "&minCpuClock=&maxCpuClock=")


_FETCH_STATS_JS = """async ({query, headers}) => {
    const base = 'https://www.3dmark.com/proxycon/ajax/';
    const r1 = await fetch(base + 'newsearch?' + query, {headers});
    if ([403, 429, 503].includes(r1.status)) return {blocked: r1.status};
    const j1 = await r1.json();
    const r2 = await fetch(base + 'medianscore?' + query, {headers});
    if ([403, 429, 503].includes(r2.status)) return {blocked: r2.status};
    const j2 = await r2.json();
    return {count: j1.resultCount, median: j2.median};
}"""


async def fetch_score(page, gpu_id: int, test_code: str = "spy P", *, retries: int = 2,
                      log: "logging.Logger | None" = None
                      ) -> "tuple[int | None, int | None, str]":
    """
    세션이 확보된 page 에서 통계 API(ajax)만 호출해
    (Graphics score 평균, 총 결과 수, 사용자용 URL) 을 반환한다.
    결과 0 건이면 (None, 0, url). 완전 실패 시 (None, None, url).
    """
    log = log or logging.getLogger("3dmark")
    url = build_url(gpu_id, test_code)
    query = _ajax_query(gpu_id, test_code)

    for attempt in range(1, retries + 2):
        try:
            res = await page.evaluate(_FETCH_STATS_JS,
                                      {"query": query, "headers": _AJAX_HEADERS})
            if res.get("blocked"):
                raise BlockedError(f"HTTP {res['blocked']}")

            count = res.get("count")
            median = res.get("median")
            if not count:                       # 0 또는 None → 결과 없음
                return None, (count or 0), url
            avg = round(median) if median is not None else None
            return avg, count, url
        except BlockedError:
            raise
        except Exception as e:  # noqa: BLE001
            log.warning(f"  gpuId={gpu_id}: 오류 {type(e).__name__}: {e} (시도 {attempt})")
            if attempt <= retries:
                await asyncio.sleep(2)

    return None, None, url


# ---------------------------------------------------------------------------
# 전체 수집 실행 (desktop / laptop 공통)
# ---------------------------------------------------------------------------
async def run_scrape(catalog: "dict[str, dict[str, int | None]]", kind: str,
                     bench: str = "timespy", *,
                     series_filter: "list[str] | None" = None,
                     min_delay: float = 1.0, max_delay: float = 3.0,
                     mode: str = "auto"):
    """
    카탈로그를 순회하며 각 GPU 의 Graphics score 평균/결과 수를 수집해 xlsx 로 저장.
    bench 는 BENCHMARKS 의 키(timespy/firestrike/portroyal/steelnomad).
    - GPU 사이에 무작위 지연(min_delay~max_delay 초) 을 둬 차단을 예방한다.
    - 차단(BlockedError) 감지 시 즉시 중단하되, 그때까지 수집분은 저장한다.
    - 진행 기록(output/{kind}/{bench}/_progress.json)을 남겨, 차단·중단 후 다시
      실행하면 이미 수집한 GPU 는 건너뛰고 이어서 수집한다. 전체 완료 시 삭제된다.
    반환: (저장경로, 차단여부)
    """
    import json
    import random
    import time
    from playwright.async_api import async_playwright

    bench_name, test_code = BENCHMARKS[bench]
    log = get_logger(kind, bench)
    log.info(f"벤치마크: {bench_name} (test={test_code})")
    progress_path = bench_dir(kind, bench) / "_progress.json"

    # 이전 진행 기록 로드 (단일 실행 내 재개)
    progress: "dict[str, list]" = {}
    if progress_path.exists():
        try:
            progress = json.loads(progress_path.read_text(encoding="utf-8"))
        except Exception:  # noqa: BLE001
            progress = {}
    if progress:
        log.info(f"이전 진행 기록 {len(progress)}개 발견 — 이어서 수집합니다.")

    def save_progress():
        progress_path.write_text(json.dumps(progress, ensure_ascii=False), encoding="utf-8")

    # 모드 결정: auto = 최근(24h 이내) 결과가 있으면 증분 업데이트(신규 GPU만)
    existing, mtime = load_latest_result(kind, bench)
    if mode == "auto":
        if existing and mtime and (time.time() - mtime < 24 * 3600):
            mode = "update"
            hrs = (time.time() - mtime) / 3600
            log.info(f"최근 수집({hrs:.1f}시간 전, {len(existing)}개)이 24시간 이내 "
                     f"→ 증분 업데이트 모드(신규 GPU만 수집, 기존 데이터 유지)")
        else:
            mode = "full"
    # update 모드: 기존 xlsx 의 gpuId 데이터를 재사용(스킵) 대상으로 둔다.
    #   단, 점수 수집에 '실패'(응답 없음 → count 도 None)한 GPU 는 known 에서 제외해
    #   최근에 시도했더라도 다시 수집하게 한다. (count==0 인 '결과 없음'은 정상이라 유지)
    known: "dict[int, tuple]" = {}
    if mode == "update":
        known = {gid: (avg, count) for gid, (s, m, avg, count, u) in existing.items()
                 if count is not None}
        skipped_fail = sum(1 for gid, (s, m, avg, count, u) in existing.items() if count is None)
        if skipped_fail:
            log.info(f"이전 수집 실패 {skipped_fail}개 — 이번에 다시 시도합니다.")
    else:
        log.info("전체 수집 모드")

    rows: "list[Row]" = []
    total = sum(len(m) for s, m in catalog.items()
                if not series_filter or s in series_filter)
    log.info(f"수집 시작: {kind}  대상 {total}개 GPU"
             + (f"  (시리즈 필터: {series_filter})" if series_filter else ""))

    done = 0
    fetched = 0          # 이번 실행에서 실제 네트워크로 가져온 수
    blocked = False
    async with async_playwright() as p:
        browser = await launch_browser(p, log)
        ctx = await make_context(browser)
        page = await ctx.new_page()
        try:
            # 세션 확보(쿠키/Origin): 검색 페이지를 1회만 로드한다.
            # 이후 각 GPU 는 이 페이지에서 통계 API(ajax)만 호출한다.
            try:
                resp = await page.goto(
                    "https://www.3dmark.com/search#advanced?test="
                    + test_code.replace(" ", "%20"),
                    wait_until="domcontentloaded", timeout=30000)
                if resp is not None and resp.status in (403, 429, 503):
                    raise BlockedError(f"HTTP {resp.status}")
                if _BLOCK_RE.search((await page.content())[:1500]):
                    raise BlockedError("차단 페이지 감지")
                await page.wait_for_timeout(1500)
                log.info("세션 확보 완료 — 통계 API 직접 호출 모드")
            except BlockedError as e:
                log.error(f"!! 시작 페이지 로드 중 차단({e}). 잠시 후 다시 실행하세요.")
                blocked = True

            for series, models in catalog.items():
                if blocked:
                    break
                if series_filter and series not in series_filter:
                    continue
                for name, gpu_id in models.items():
                    done += 1
                    if gpu_id is None:
                        log.info(f"[{done}/{total}] {series} / {name} — gpuId 미등록, 건너뜀")
                        rows.append((series, name, None, None, ""))
                        continue

                    key = str(gpu_id)
                    # 이미 수집된 항목은 재사용 (단일 실행 내 재개)
                    if key in progress:
                        avg, count = progress[key]
                        rows.append((series, name, avg, count, build_url(gpu_id, test_code)))
                        log.info(f"[{done}/{total}] {series} / {name} (id={gpu_id})"
                                 f"  →  (재개) 평균={avg}  결과수={count}")
                        continue
                    # 증분 업데이트: 기존 xlsx 에 있던 GPU 는 그대로 두고 건너뛴다
                    if gpu_id in known:
                        avg, count = known[gpu_id]
                        rows.append((series, name, avg, count, build_url(gpu_id, test_code)))
                        log.info(f"[{done}/{total}] {series} / {name} (id={gpu_id})"
                                 f"  →  (기존 유지) 평균={avg}  결과수={count}")
                        continue

                    try:
                        avg, count, url = await fetch_score(page, gpu_id, test_code, log=log)
                    except BlockedError as e:
                        log.error(f"!! CloudFront/WAF 차단 감지({e}). 수집을 중단합니다.")
                        log.error("   잠시(수십 분~수 시간) 후 다시 실행하면 "
                                  "이어서 수집합니다. 또는 --min-delay/--max-delay 를 늘리세요.")
                        blocked = True
                        break

                    rows.append((series, name, avg, count, url))
                    log.info(f"[{done}/{total}] {series} / {name} (id={gpu_id})"
                             f"  →  평균={avg}  결과수={count}")
                    # 성공/0건만 기록(완전 실패는 다음 실행에서 재시도)
                    if avg is not None or count is not None:
                        progress[key] = [avg, count]
                        save_progress()
                    fetched += 1
                    # GPU 사이 무작위 지연
                    await asyncio.sleep(random.uniform(min_delay, max_delay))
                if blocked:
                    break
        finally:
            await browser.close()

    path = save_xlsx(rows, kind, bench)
    suffix = "  [차단으로 중단됨]" if blocked else ""
    ok = sum(1 for r in rows if r[2] is not None)
    log.info(f"저장 완료: {path}")
    log.info(f"총 {len(rows)}행 (점수 확보 {ok}개, 이번 실행 신규 {fetched}개){suffix}")

    if blocked:
        log.info(f"진행 기록 보관됨({len(progress)}개). 다시 실행하면 이어서 수집합니다.")
    else:
        progress_path.unlink(missing_ok=True)
        log.info("전체 수집 완료 — 진행 기록을 초기화했습니다.")
    return path, blocked


# ---------------------------------------------------------------------------
# Excel 저장
# ---------------------------------------------------------------------------
def save_xlsx(rows: "list[Row]", kind: str, bench: str = "timespy") -> Path:
    """
    rows 를 output/{kind}/{bench}/ 에 .xlsx 로 저장한다.
    컬럼: 시리즈 / 모델명 / 평균 점수 / 총 결과 수 / 링크
    """
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    d = bench_dir(kind, bench)
    path = d / f"3dmark_{kind}_{bench}_scores_{ts}.xlsx"

    wb = Workbook()
    ws = wb.active
    ws.title = "Time Spy Graphics"

    headers = ["시리즈", "모델명", "평균 점수", "총 결과 수", "링크"]
    ws.append(headers)

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="305496")
    for col, _ in enumerate(headers, start=1):
        c = ws.cell(row=1, column=col)
        c.font = header_font
        c.fill = header_fill
        c.alignment = Alignment(horizontal="center", vertical="center")

    link_font = Font(color="0563C1", underline="single")
    for series, model, avg, count, url in rows:
        r = ws.max_row + 1
        ws.cell(row=r, column=1, value=series)
        ws.cell(row=r, column=2, value=model)
        ws.cell(row=r, column=3, value=avg)            # None → 빈 셀
        ws.cell(row=r, column=4, value=count)
        link_cell = ws.cell(row=r, column=5, value=url)
        link_cell.hyperlink = url
        link_cell.font = link_font

    # 숫자 천단위 콤마 서식
    for r in range(2, ws.max_row + 1):
        ws.cell(row=r, column=3).number_format = "#,##0"
        ws.cell(row=r, column=4).number_format = "#,##0"

    # 컬럼 너비
    widths = [10, 22, 12, 12, 70]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:E{ws.max_row}"

    wb.save(path)
    # 신규 파일을 만들지 않고 '기존 파일 업데이트(날짜만 갱신)' 효과:
    # 같은 폴더의 이전 결과 xlsx 는 삭제해 항상 1개만 유지한다.
    for old in d.glob("3dmark_*_scores_*.xlsx"):
        if old != path:
            try:
                old.unlink()
            except Exception:  # noqa: BLE001
                pass
    return path


# ---------------------------------------------------------------------------
# 로깅
# ---------------------------------------------------------------------------
def get_logger(kind: str, bench: str = "timespy") -> logging.Logger:
    # Windows cp949 콘솔에서 em dash(—) 등 미지원 문자로 죽지 않도록 안전 처리
    try:
        sys.stdout.reconfigure(errors="replace")
    except Exception:  # noqa: BLE001
        pass

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = bench_dir(kind, bench) / f"run_{ts}.log"

    logger = logging.getLogger(f"3dmark.{kind}.{bench}")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    fmt = logging.Formatter("%(asctime)s  %(levelname)-7s  %(message)s", "%H:%M:%S")

    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    logger.addHandler(sh)

    fh = logging.FileHandler(log_path, encoding="utf-8")
    fh.setFormatter(fmt)
    logger.addHandler(fh)

    logger.info(f"로그 파일: {log_path}")
    return logger
